package com.robindrew.trading.igindex.platform.rest.executor.getpositions;

public enum InstrumentType {

	BINARY, BUNGEE_CAPPED, BUNGEE_COMMODITIES, BUNGEE_CURRENCIES, BUNGEE_INDICES, COMMODITIES, CURRENCIES, INDICES, OPT_COMMODITIES, OPT_CURRENCIES, OPT_INDICES, OPT_RATES, OPT_SHARES, RATES, SECTORS, SHARES, SPRINT_MARKET, TEST_MARKET, UNKNOWN;
}
